### ISSUE TITLE
Failing website link on github

### ISSUE THREAD

**Issue by Cyclodex** [kontent-ai/sample-app-next-js#47]
Hi.

Just a small info / request not related to the code itself, but to your project hosted on github.
While I have seen updates to the readme, just recently, a very prominent link is not working and probably needs an update too:

The website link of the github repo.
![image](https://github.com/kontent-ai/sample-app-next-js/assets/840929/dd05f1e0-83dc-472b-a053-fb7b0b64db67)

Looking forward to check out this repo further!

Cheers Fabian

**Comment by Simply007** [comment]
I fxed it to https://ficto-healthtech.vercel.app/ for now - @IvanKiral for notice :)

**Comment by JiriLojda** [comment]
Thank you @Cyclodex for the report and @Simply007 for the fix. I will close this issue now. If you'd like to discuss anything else feel free to reopen it or create another one.
