### ISSUE TITLE
https:dev starts with wrong proxy

### ISSUE THREAD

**Issue by hejtmii** [kontent-ai/sample-app-next-js#49]
### Brief bug description

When starting the app with https:dev and localhost:3000 taken, it creates a wrong HTTPS proxy

What went wrong?

### Repro steps

Have localhost:3000 used by another process

Start https:dev

It makes proxy to localhost:3000 but later starts the site on localhost:3002 (or whatever is available)

![image](https://github.com/kontent-ai/sample-app-next-js/assets/11004903/ec8353e0-e271-44a6-a077-7e70470b1a91)

### Expected behavior

The proxy is created to a port that is actually used to run the site

### Test environment

Windows

**Comment by JiriLojda** [comment]
Thank you for the feedback. It seems the Next's `npm run dev` command tries other ports when the `3000` port is used, but the proxy is hard coded to redirect to the `3000` port.
That being said, I don't think it's worth complicating the command to make it work in this scenario. You can just run the two commands in parallel yourself (`npm run dev`, `npm run https:proxy -- --target 3002`). But we will make it clearer in the readme and have the `https:dev` fail when the port `3000` is in use.
